print("Welcome to the Band Name Generator\n")
city_name = input("What's name of the city ou grew up in? ")
print(city_name)
pet_name = input("What's your pet's name: ")
print(pet_name)
print("Your band name could be" + ' ' + city_name +' ' + pet_name)
